"""
Production Inference and Live Scoring Module.

This script acts as the operational bridge between the trained machine learning 
artifacts and the live decision service. It is designed for low-latency inference: 
it ingests new raw telemetry, applies stateless feature engineering using pre-fitted 
scalers, generates quantile predictions, applies Conformal Calibration, and outputs 
actionable maintenance intervals.


"""

import argparse
import pandas as pd
import numpy as np
import xgboost as xgb
import pickle
import os
import sys
from typing import Optional

# Import custom feature factory and uncertainty functions
from src.features import build_features
from src.uncertainty import apply_cqr_bounds

def predict_rul(input_data_path: str, model_dir: str = "data/") -> Optional[pd.DataFrame]:
    """
    Executes the end-to-end production inference pipeline for new engine telemetry.
    
    This function is strictly stateless. It does not fit or train any data. It relies 
    entirely on the serialized artifacts (scaler, q_hat, models) generated by the 
    batch training pipeline (`train.py`) to guarantee no data leakage and rapid execution.

    Args:
        input_data_path (str): The file path to the incoming raw sensor telemetry.
        model_dir (str, optional): The directory containing the `.pkl` and `.json` 
                                   model artifacts. Defaults to "data/".

    Returns:
        Optional[pd.DataFrame]: A DataFrame containing the Unit ID, Median RUL, 
                                Lower/Upper Bounds, and Interval Width. Returns None 
                                if required artifacts are missing.
    """
    print(f"=== RUNNING INFERENCE ON: {input_data_path} ===\n")
    
    # -------------------------------------------------------------------------
    # 1. Load Pre-Trained Artifacts
    # -------------------------------------------------------------------------
    # In a production environment, the inference script must never recalculate 
    # global statistics. We load the frozen state of the training environment.
    try:
        print(">> Loading models, scaler, and conformal calibration penalty...")
        with open(os.path.join(model_dir, 'scaler.pkl'), 'rb') as f:
            scaler = pickle.load(f)
        with open(os.path.join(model_dir, 'active_sensors.pkl'), 'rb') as f:
            active_sensors = pickle.load(f)
        with open(os.path.join(model_dir, 'q_hat.pkl'), 'rb') as f:
            q_hat = pickle.load(f)
            
        model_50 = xgb.XGBRegressor()
        model_50.load_model(os.path.join(model_dir, 'xgb_model_50.json'))
        
        model_05 = xgb.XGBRegressor()
        model_05.load_model(os.path.join(model_dir, 'xgb_model_05.json'))
        
        model_95 = xgb.XGBRegressor()
        model_95.load_model(os.path.join(model_dir, 'xgb_model_95.json'))
        
    except FileNotFoundError as e:
        print(f"ERROR: Model artifacts not found. Details: {e}")
        print("Please ensure 'src/train.py' has been run to generate the required .pkl and .json files.")
        return None

    # -------------------------------------------------------------------------
    # 2. Ingest Live Telemetry
    # -------------------------------------------------------------------------
    print(">> Ingesting raw sensor telemetry stream...")
    cols = ['unit', 'cycle', 'op1', 'op2', 'op3'] + [f's{i}' for i in range(1, 22)]
    try:
        new_data = pd.read_csv(input_data_path, sep=r'\s+', header=None, names=cols)
    except FileNotFoundError:
        print(f"ERROR: Input telemetry file not found at {input_data_path}.")
        return None
    
    # -------------------------------------------------------------------------
    # 3. Stateless Feature Engineering
    # -------------------------------------------------------------------------
    print(">> Extracting temporal features (rolling windows & physical velocity)...")
    # Apply the exact same rolling window logic used in training, utilizing the 
    # frozen MinMaxScaler to prevent distribution shift.
    features_df = build_features(new_data, scaler, active_sensors)
    
    # Isolate the Current Operating State:
    # We only want to predict the RUL from the most recent cycle received for each engine.
    current_state = features_df.groupby('unit').tail(1).sort_values('unit').reset_index(drop=True)
    
    exclude = ['unit', 'cycle', 'RUL', 'op1', 'op2', 'op3'] + active_sensors
    feature_cols = [c for c in current_state.columns if c not in exclude]
    
    X_live = current_state[feature_cols]
    
    # -------------------------------------------------------------------------
    # 4. Model Inference & Uncertainty Calibration
    # -------------------------------------------------------------------------
    print(">> Generating Predictions and Conformal Uncertainty Bounds...")
    pred_50 = model_50.predict(X_live)
    pred_05 = model_05.predict(X_live)
    pred_95 = model_95.predict(X_live)
    
    # Apply Conformal Penalty (q_hat) to guarantee the ~90% empirical coverage rate
    lower_bound, upper_bound = apply_cqr_bounds(pred_05, pred_95, q_hat)
    
    # -------------------------------------------------------------------------
    # 5. Format Output for the Decision Service
    # -------------------------------------------------------------------------
    results = pd.DataFrame({
        'Engine_Unit': current_state['unit'],
        'Predicted_RUL_Median': np.round(pred_50, 1),
        'CQR_Lower_Bound': np.round(lower_bound, 1),
        'CQR_Upper_Bound': np.round(upper_bound, 1),
        'Urgency_Interval_Width': np.round(upper_bound - lower_bound, 1)
    })
    
    print("\n=== INFERENCE RESULTS (TOP 5 ENGINES) ===")
    print(results.head().to_markdown(index=False))
    
    # Export to CSV for downstream dashboarding or scheduling services
    output_file = os.path.join(model_dir, 'live_predictions.csv')
    results.to_csv(output_file, index=False)
    print(f"\n Pipeline complete. Predictions pushed to {output_file}")
    
    return results

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Production Inference: Predict RUL on new telemetry data.")
    parser.add_argument("--input", type=str, required=True, help="Absolute or relative path to the new raw sensor data (e.g., data/test_FD001.txt)")
    parser.add_argument("--model_dir", type=str, default="/home/user/risk-aware-predictive-maintenance/data/archive/CMaps/", help="Directory containing the saved model artifacts.")
    args = parser.parse_args()
    
    # Execute the pipeline
    predict_rul(args.input, args.model_dir)